import type { Metadata } from 'next';
import './globals.css';
import { Container, Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import styles from '@/styles/Main.module.scss';
import { ThemeProvider } from './theme-provider';
import Navbar from '@/components/NavBar';
import '@/api/config';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          enableSystem
          disableTransitionOnChange={false}
        >
          <Theme>
            <Navbar />
            <Container size={'4'}>
              <div className={styles.mainContainer}>{children}</div>
            </Container>
          </Theme>
        </ThemeProvider>
      </body>
    </html>
  );
}
