import type { Metadata } from 'next';
import '@/styles/global.css';
import './globals.css';
import { Theme } from '@radix-ui/themes';
import '@radix-ui/themes/styles.css';
import { ThemeProvider } from './theme-provider';
import styles from '@/styles/Main.module.scss';
import NavBar from '@/components/navbar/NavBar';
import React from 'react';
import Footer from '@/components/footer/Footer';
import StoreProvider from '@/app/store-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            enableSystem
            disableTransitionOnChange={false}
          >
            <Theme>
              <NavBar />
              <div className={styles.mainContainer}>
                {children}
              </div>
              <Footer />
            </Theme>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
