// This file is auto-generated by @hey-api/openapi-ts

export const UserRegisterDTOSchema = {
    type: 'object',
    properties: {
        nickname: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        password: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseUserVOSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/UserVO'
        }
    }
} as const;

export const UserVOSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        nickname: {
            type: 'string'
        },
        email: {
            type: 'string'
        },
        avatar: {
            type: 'string'
        },
        created: {
            type: 'string'
        },
        oauthProvider: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseTagSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/Tag'
        }
    }
} as const;

export const TagSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        name: {
            type: 'string'
        },
        created: {
            type: 'string',
            format: 'date-time'
        },
        updated: {
            type: 'string',
            format: 'date-time'
        },
        deleted: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ArticleDTOSchema = {
    type: 'object',
    properties: {
        title: {
            type: 'string'
        },
        content: {
            type: 'string'
        },
        cover: {
            type: 'string'
        },
        tags: {
            type: 'string'
        },
        status: {
            type: 'string'
        }
    }
} as const;

export const ApiResponseArticleSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            '$ref': '#/components/schemas/Article'
        }
    }
} as const;

export const ArticleSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'integer',
            format: 'int64'
        },
        title: {
            type: 'string'
        },
        content: {
            type: 'string'
        },
        authorId: {
            type: 'integer',
            format: 'int64'
        },
        cover: {
            type: 'string'
        },
        views: {
            type: 'integer',
            format: 'int32'
        },
        likes: {
            type: 'integer',
            format: 'int32'
        },
        comments: {
            type: 'integer',
            format: 'int32'
        },
        status: {
            type: 'string'
        },
        created: {
            type: 'string',
            format: 'date-time'
        },
        updated: {
            type: 'string',
            format: 'date-time'
        },
        deleted: {
            type: 'string',
            format: 'date-time'
        }
    }
} as const;

export const ApiResponseObjectSchema = {
    type: 'object',
    properties: {
        code: {
            type: 'integer',
            format: 'int32'
        },
        msg: {
            type: 'string'
        },
        data: {
            type: 'object'
        }
    }
} as const;