// This file is auto-generated by @hey-api/openapi-ts

export type UserRegisterDTO = {
    nickname?: string;
    email?: string;
    password?: string;
};

export type ApiResponseUserVO = {
    code?: number;
    msg?: string;
    data?: UserVO;
};

export type UserVO = {
    id?: string;
    nickname?: string;
    email?: string;
    avatar?: string;
    createdAt?: string;
    oauthProvider?: string;
};

export type ApiResponseTag = {
    code?: number;
    msg?: string;
    data?: Tag;
};

export type Tag = {
    id?: number;
    name?: string;
    created?: string;
    updated?: string;
    deleted?: string;
};

export type ArticleDTO = {
    title?: string;
    content?: string;
    cover?: string;
    categoryId?: number;
    tags?: string;
    status?: string;
};

export type ApiResponseArticleVO = {
    code?: number;
    msg?: string;
    data?: ArticleVO;
};

export type ArticleVO = {
    id?: string;
    title?: string;
    content?: string;
    authorName?: string;
    cover?: string;
    views?: number;
    likes?: number;
    comments?: number;
    status?: 'PUBLISHED' | 'DRAFT';
    createdAt?: string;
    updatedAt?: string;
    deletedAt?: string;
};

export type status = 'PUBLISHED' | 'DRAFT';

export type ApiResponseObject = {
    code?: number;
    msg?: string;
    data?: {
        [key: string]: unknown;
    };
};

export type ApiResponseArticleView = {
    code?: number;
    msg?: string;
    data?: ArticleView;
};

export type ArticleView = {
    id?: string;
    title?: string;
    content?: string;
    authorName?: string;
    cover?: string;
    views?: number;
    likes?: number;
    comments?: number;
    createdAt?: string;
    updatedAt?: string;
};

export type RegisterApiData = {
    body: UserRegisterDTO;
};

export type RegisterApiResponse = (ApiResponseUserVO);

export type RegisterApiError = unknown;

export type AddNewTagApiData = {
    query: {
        tagName: string;
    };
};

export type AddNewTagApiResponse = (ApiResponseTag);

export type AddNewTagApiError = unknown;

export type AddArticleApiData = {
    body: ArticleDTO;
};

export type AddArticleApiResponse = (ApiResponseArticleVO);

export type AddArticleApiError = unknown;

export type HelloResponse = (ApiResponseObject);

export type HelloError = unknown;

export type ViewOneArticleApiData = {
    path: {
        id: number;
    };
};

export type ViewOneArticleApiResponse = (ApiResponseArticleView);

export type ViewOneArticleApiError = unknown;