// This file is auto-generated by @hey-api/openapi-ts

export type UserRegisterDTO = {
    nickname?: string;
    email?: string;
    password?: string;
};

export type ApiResponseUserVO = {
    code?: number;
    msg?: string;
    data?: UserVO;
};

export type UserVO = {
    id?: number;
    nickname?: string;
    email?: string;
    avatar?: string;
    created?: string;
    oauthProvider?: string;
};

export type ApiResponseTag = {
    code?: number;
    msg?: string;
    data?: Tag;
};

export type Tag = {
    id?: number;
    name?: string;
    created?: string;
    updated?: string;
    deleted?: string;
};

export type ArticleDTO = {
    title?: string;
    content?: string;
    cover?: string;
    tags?: string;
    status?: string;
};

export type ApiResponseArticle = {
    code?: number;
    msg?: string;
    data?: Article;
};

export type Article = {
    id?: number;
    title?: string;
    content?: string;
    authorId?: number;
    cover?: string;
    views?: number;
    likes?: number;
    comments?: number;
    status?: string;
    created?: string;
    updated?: string;
    deleted?: string;
};

export type ApiResponseObject = {
    code?: number;
    msg?: string;
    data?: {
        [key: string]: unknown;
    };
};

export type RegisterApiData = {
    body: UserRegisterDTO;
};

export type RegisterApiResponse = (ApiResponseUserVO);

export type RegisterApiError = unknown;

export type AddNewTagApiData = {
    query: {
        tagName: string;
    };
};

export type AddNewTagApiResponse = (ApiResponseTag);

export type AddNewTagApiError = unknown;

export type AddArticleApiData = {
    body: ArticleDTO;
};

export type AddArticleApiResponse = (ApiResponseArticle);

export type AddArticleApiError = unknown;

export type HelloResponse = (ApiResponseObject);

export type HelloError = unknown;