spring:
  datasource:
    username: grtsinry43
    password: 5289
  data:
    mongodb:
      uri: mongodb://localhost:27017/grtblog
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 372966461575-kk595f182icrn0e9gf83m2ahdqsec64a.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/google"
            client-name: Google
          github:
            client-id: Ov23lifMNW0dq416RGwX
            client-secret: da78348df8c03040118c4dd2485ee9fbcab8bee1
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/github"
            scope: user:email
            client-name: Github
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
#  elasticsearch:
#    uris: http://localhost:9200
#    username: elastic
#    password: dVMcgw4tic+SW9fHkQkc
  mail:
    host: smtp.larksuite.com
    port: 587
    username: notification@grtsinry43.com
    password: WWgRythjFS9clX3p
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    default-encoding: UTF-8

com:
  grtsinry43:
    wx:
      appid: 1
      secret: 2
    secret_key: YODD5+ksIt7qHV/Jp9NGkaEpjpgExVXjelXQlYa9Gh4r787rhnfSpCS/XDFaUzJOFurtYlQ+XwmsjZgp3L4mUw==
    github:
      clientId: Ov23lifMNW0dq416RGwX
      clientSecret: d00aab92ddf7de28954671dc4f2d10cae6e2e212
      redirectUri: http://localhost:8080/login/oauth2/code/github
    deepseek-api-key: sk-131671151c9e4617a512d66d5573e40a
#    deepseek-api-key: c1fb73e7-412c-405e-82a0-56ba0fdaa59e
    meilisearch:
      url: http://localhost:7700
      apiKey: masterKey