snowflake:
  data-center-id: 2025
  machine-id: 2025

com:
  grtsinry43:
    secret_key: "dobase"
    meilisearch:
      url:"localhost:8888"
      apiKey:"abcdef"
    deepseek-api-key: ""
    github:
      clientId: ""
      clientSecret: ""
      redirectUri: ""

recommender:
  service:
    url: "http://localhost:8080"
spring:
  mail:
    username: ""








