snowflake:
  data-center-id: 2025
  machine-id: 2025

com:
  grtsinry43:
    secret_key: "dobase"
    meilisearch:
      url: "localhost:7700"
      apiKey: "abcdef"
    deepseek-api-key: ""
    github:
      clientId: ""
      clientSecret: ""
      redirectUri: ""

recommender:
  service:
    url: "http://localhost:8081"
spring:
  mail:
    username: ""








